language: python
python:
  - '3.7' 
install:
  - python setup.py install
deploy:
  - provider: pypi
    user: wonderqs
    password: ${PYPI_PASSWORD}
    on:
      python: 3.7
      tags: true
      branch: master
